services:
  frontend:
    image: seal-frontend:activity
    mem_limit: 256m
    cpus: 0.50

  backend:
    image: seal-backend:activity
    mem_limit: 384m
    cpus: 0.75

  nginx:
    mem_limit: 64m
    cpus: 0.25

  certbot:
    mem_limit: 96m
    cpus: 0.25
